//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bookEntities1 : DbContext
    {
        public bookEntities1()
            : base("name=bookEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Auteur> Auteurs { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Livre> Livres { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
    }
}
