//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livre
    {
        public int Id { get; set; }
        public string Titre { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateSortie { get; set; }
        public Nullable<int> IdAuteur { get; set; }
        public Nullable<int> IdGenre { get; set; }
        public string image { get; set; }
    
        public virtual Auteur Auteur { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
